#!/usr/bin/perl
use strict;
use warnings;
use VHS;

my $arg = shift @ARGV;
exit unless $arg;

my %msg_map = (
    'open' => 'My door opened!',
    closed => 'My door closed!',
    test   => 'My systems are being tested!',
);

if (my $msg = $msg_map{$arg}) {
    my $image_url = VHS->take_picture() if $arg eq 'open';;
    VHS->send_tweet($msg, $image_url);
}

exit;


