#!/usr/bin/perl
use strict;
use warnings;
use VHS;

my $arg = shift @ARGV;
my $who = shift @ARGV;
exit unless $arg;

if ($arg =~ m/(\d+(?:\.\d+)?C)/) {
    my $msg = "Temperature at VHS: $1";
    $msg = "\@$who - $msg" if $who;
    VHS->send_tweet($msg);
}
