#!/usr/bin/perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../../lib";
use VHS;

my $arg = shift @ARGV;
exit unless $arg;

if ($arg =~ m/(\d+(?:\.\d+)?C)/) {

    # Later:
    VHS->send_tweet("Temperature at VHS: $1");
}
